/* Question bank. p = exam part (1–4 Use of English, 5 = reading), tp = topic id, lv = difficulty 1–3.
   mc: o = options, a = index. gap/wf: a = accepted answers. kwt: s1 / k (key word) / s2 with ___ / a = accepted gap fills. */
window.BANK = [
/* ---------- PART 1 · multiple-choice cloze ---------- */
{p:1,tp:"coll",lv:1,s:"Before making a decision, you should ___ into account all the possible consequences.",o:["take","bring","put","hold"],a:0,ex:"Fixed collocation: take sth into account = consider it."},
{p:1,tp:"coll",lv:2,s:"The new evidence has ___ serious doubts about the reliability of the original study.",o:["cast","thrown","laid","put"],a:0,ex:"cast doubt(s) on/about = make something seem less certain. 'Throw light on' exists, but not 'throw doubts'."},
{p:1,tp:"coll",lv:2,s:"Years of overwork eventually took their ___ on his health.",o:["toll","price","cost","charge"],a:0,ex:"take a/its toll on = have a damaging effect over time."},
{p:1,tp:"coll",lv:2,s:"The campaign aims to ___ awareness of the dangers of plastic waste.",o:["raise","rise","lift","grow"],a:0,ex:"raise awareness (transitive verb raise + object). Rise is intransitive."},
{p:1,tp:"coll",lv:3,s:"The government has come under ___ criticism for its handling of the crisis.",o:["fierce","hard","thick","deep"],a:0,ex:"fierce/heavy/strong criticism. 'Hard criticism' is not a natural collocation."},
{p:1,tp:"coll",lv:2,s:"It is ___ knowledge that the company is in financial difficulties.",o:["common","general","usual","ordinary"],a:0,ex:"common knowledge = something most people know."},
{p:1,tp:"coll",lv:3,s:"The architect's plans have yet to ___ with the approval of the council.",o:["meet","find","receive","gain"],a:0,ex:"meet with approval (fixed). You can receive/gain approval, but 'with' after the gap only fits 'meet'."},
{p:1,tp:"coll",lv:2,s:"She was ___ disappointed when she wasn't selected for the team.",o:["bitterly","heavily","sorely","strongly"],a:0,ex:"bitterly disappointed is the strong collocation. 'Sorely' goes with missed/tempted."},
{p:1,tp:"coll",lv:3,s:"Tourism has given ___ to a number of environmental problems on the island.",o:["rise","cause","birth","way"],a:0,ex:"give rise to = cause. 'Give birth to' is literal/new ideas; 'give way to' = be replaced by."},
{p:1,tp:"coll",lv:2,s:"Managers must ___ a balance between efficiency and staff wellbeing.",o:["strike","hit","make","beat"],a:0,ex:"strike a balance (between X and Y)."},
{p:1,tp:"coll",lv:3,s:"The diaries ___ fascinating light on everyday life in the 18th century.",o:["shed","pour","spill","give"],a:0,ex:"shed/throw light on = help to explain."},
{p:1,tp:"confus",lv:2,s:"There is a severe ___ of qualified nurses in rural hospitals.",o:["shortage","lack","absence","want"],a:0,ex:"a shortage of = not enough supply of something needed. 'Lack' is also possible with 'of', but 'severe shortage' is the established collocation for staff/supplies."},
{p:1,tp:"confus",lv:2,s:"The decision to close the factory will ___ thousands of families.",o:["affect","effect","impress","result"],a:0,ex:"affect is the verb (= have an influence on). 'Effect' as a verb means to bring about; 'result' needs 'in'."},
{p:1,tp:"confus",lv:3,s:"The committee ___ of representatives from every department.",o:["consists","comprises","includes","composes"],a:0,ex:"consist OF. Comprise takes no preposition (the committee comprises representatives)."},
{p:1,tp:"confus",lv:2,s:"He ___ having taken the money, despite the overwhelming evidence.",o:["denied","refused","rejected","declined"],a:0,ex:"deny + -ing = say you did not do it. refuse/decline + to-infinitive; reject + noun."},
{p:1,tp:"confus",lv:3,s:"His ___ remarks deeply offended several members of the audience.",o:["insensitive","insensible","unsensitive","nonsensical"],a:0,ex:"insensitive = not considering people's feelings. 'Insensible' = unconscious/unaware."},
{p:1,tp:"confus",lv:2,s:"The ___ cost of the project turned out to be twice the estimate.",o:["actual","current","present","factual"],a:0,ex:"actual = real (vs estimated). Spanish 'actual' = current, a classic false friend."},
{p:1,tp:"confus",lv:3,s:"The hotel ___ a beautiful bay surrounded by cliffs.",o:["overlooks","oversees","overviews","overhangs"],a:0,ex:"overlook = have a view of from above. Oversee = supervise."},
{p:1,tp:"confus",lv:2,s:"Volunteers are ___ to a free meal at the end of each shift.",o:["entitled","eligible","allowed","qualified"],a:0,ex:"be entitled TO something (a right). 'Eligible for', 'allowed to + verb'."},
{p:1,tp:"pv",lv:1,s:"The outdoor concert was ___ off because of the storm warning.",o:["called","put","set","taken"],a:0,ex:"call off = cancel. put off = postpone."},
{p:1,tp:"pv",lv:2,s:"It took her several months to get ___ the shock of losing her job.",o:["over","through","by","across"],a:0,ex:"get over = recover from."},
{p:1,tp:"pv",lv:2,s:"The police have not ruled ___ the possibility that the fire was started deliberately.",o:["out","off","away","down"],a:0,ex:"rule out = exclude as a possibility."},
{p:1,tp:"pv",lv:2,s:"Despite months of negotiations, the deal fell ___ at the last minute.",o:["through","apart","out","off"],a:0,ex:"fall through = fail to happen (plans, deals). Fall apart = break into pieces."},
{p:1,tp:"pv",lv:3,s:"The minister tried to ___ down the seriousness of the situation.",o:["play","turn","put","bring"],a:0,ex:"play down = make seem less important."},
{p:1,tp:"pv",lv:3,s:"The film didn't ___ up to the expectations created by its trailer.",o:["live","measure","keep","stand"],a:0,ex:"live up to expectations. 'Measure up to' also exists but is followed by a standard/person; with 'expectations' live up to is the fixed collocation."},
{p:1,tp:"pv",lv:2,s:"Our hard work finally ___ off when we won the contract.",o:["paid","took","went","came"],a:0,ex:"pay off = bring success after effort."},
{p:1,tp:"pv",lv:3,s:"The company is going to ___ out its older models over the next two years.",o:["phase","weed","rule","wipe"],a:0,ex:"phase out = gradually stop using/producing."},
{p:1,tp:"idiom",lv:2,s:"I was completely at a ___ as to how to respond to such a rude question.",o:["loss","miss","lack","gap"],a:0,ex:"at a loss = not knowing what to do or say."},
{p:1,tp:"idiom",lv:2,s:"The outcome of the election is by no ___ certain.",o:["means","way","chance","account"],a:0,ex:"by no means = not at all."},
{p:1,tp:"idiom",lv:3,s:"She was on the ___ of giving up when she finally received a job offer.",o:["verge","edge","border","limit"],a:0,ex:"on the verge of + -ing = very close to."},
{p:1,tp:"idiom",lv:2,s:"It hasn't all been plain ___, but the business is now doing well.",o:["sailing","running","going","driving"],a:0,ex:"plain sailing = easy progress without problems."},
{p:1,tp:"idiom",lv:3,s:"Good, affordable flats in the city centre are few and far ___.",o:["between","apart","away","off"],a:0,ex:"few and far between = rare."},
{p:1,tp:"deppr",lv:2,s:"Elderly people are particularly ___ to infections during the winter months.",o:["susceptible","exposed","inclined","sensitive"],a:0,ex:"susceptible to infection. 'Prone to' would also work; 'exposed to' means in contact with."},
{p:1,tp:"deppr",lv:2,s:"All visitors must ___ with the safety regulations at all times.",o:["comply","obey","follow","respect"],a:0,ex:"comply WITH. obey/follow/respect take a direct object."},
{p:1,tp:"deppr",lv:3,s:"She ___ her success to the support of her family.",o:["attributes","credits","assigns","thanks"],a:0,ex:"attribute sth TO sb/sth. 'Credit' would need 'credits her family with her success'."},
{p:1,tp:"link",lv:3,s:"___ as I admire his talent, I can't approve of his behaviour.",o:["Much","Even","Though","However"],a:0,ex:"Much as = although (+ clause), formal. Note no comma between 'Much as' and the clause."},
{p:1,tp:"link",lv:2,s:"The project was cancelled ___ to a lack of funding.",o:["owing","because","thanks","as"],a:0,ex:"owing to / due to + noun. 'Because' needs 'of'."},
{p:1,tp:"coll",lv:1,s:"You'll have ___ opportunity to ask questions at the end of the talk.",o:["ample","wide","broad","large"],a:0,ex:"ample opportunity = more than enough."},
{p:1,tp:"coll",lv:3,s:"The report makes a ___ generalisation about young people and technology.",o:["sweeping","spreading","extensive","full"],a:0,ex:"a sweeping generalisation/statement."},
{p:1,tp:"coll",lv:2,s:"The scheme was set up with the ___ of reducing youth unemployment.",o:["aim","target","point","direction"],a:0,ex:"with the aim of + -ing = in order to."},
{p:1,tp:"confus",lv:3,s:"Demand for the product has far ___ the manufacturer's expectations.",o:["exceeded","excelled","overcome","overtaken"],a:0,ex:"exceed expectations/limits. Excel = be very good at."},

/* ---------- PART 2 · open cloze ---------- */
{p:2,tp:"link",lv:2,s:"___ the bad weather, the festival attracted record crowds.",a:["despite","notwithstanding"],ex:"Despite + noun (no 'of'). 'In spite' needs 'of', which would be two words."},
{p:2,tp:"link",lv:3,s:"The new system is one ___ customers can track their orders in real time.",a:["whereby"],ex:"whereby = by which (formal relative)."},
{p:2,tp:"link",lv:3,s:"He hardly ever cooks, ___ alone bakes his own bread.",a:["let"],ex:"let alone = and certainly not (after a negative)."},
{p:2,tp:"link",lv:2,s:"She spoke quietly so ___ not to wake the baby.",a:["as"],ex:"so as (not) to = in order (not) to."},
{p:2,tp:"link",lv:3,s:"The changes, ___ minor, made a real difference.",a:["albeit","though","although"],ex:"albeit = although (+ adjective/phrase). 'though/although' + adj is also accepted."},
{p:2,tp:"link",lv:2,s:"You can borrow my car as ___ as you bring it back by Friday.",a:["long"],ex:"as long as = on condition that."},
{p:2,tp:"link",lv:2,s:"Prices haven't come down. If ___, they've gone up.",a:["anything"],ex:"if anything = (introducing a stronger contrasting idea)."},
{p:2,tp:"inv",lv:2,s:"No ___ had I closed the door than the phone rang.",a:["sooner"],ex:"No sooner + inverted past perfect … than."},
{p:2,tp:"inv",lv:2,s:"Not ___ did she apologise, but she also offered to pay for the damage.",a:["only"],ex:"Not only + inversion … but also."},
{p:2,tp:"inv",lv:3,s:"Little ___ they know what was waiting for them at home.",a:["did"],ex:"Little + did + subject + infinitive = they had no idea."},
{p:2,tp:"inv",lv:3,s:"Only ___ the results were published did the scale of the problem become clear.",a:["when","after","once"],ex:"Only when/after + clause, then inversion in the main clause (did the scale…)."},
{p:2,tp:"inv",lv:3,s:"___ it not for your help, I would never have finished on time.",a:["were"],ex:"Were it not for = If it weren't for. 'Had it not been for' would need 'been', so only Were fits."},
{p:2,tp:"cleft",lv:2,s:"___ I need right now is a long holiday.",a:["what","all"],ex:"Wh-cleft: What I need is… / All I need is…"},
{p:2,tp:"cleft",lv:2,s:"It wasn't ___ I read the instructions that I understood the problem.",a:["until","till"],ex:"It wasn't until … that …"},
{p:2,tp:"rel",lv:2,s:"The museum received 400 letters, most of ___ were from children.",a:["which"],ex:"Quantifier + of + which (things)."},
{p:2,tp:"rel",lv:2,s:"The candidates, none of ___ had any experience, were all rejected.",a:["whom"],ex:"none of whom (people, after a preposition)."},
{p:2,tp:"rel",lv:3,s:"We arrived at midnight, by ___ time the restaurant had closed.",a:["which"],ex:"by which time = and by that time."},
{p:2,tp:"rel",lv:2,s:"That's the writer ___ novel won the award last year.",a:["whose"],ex:"whose = possession."},
{p:2,tp:"comp",lv:2,s:"The ___ you practise, the more confident you'll become.",a:["more"],ex:"The + comparative …, the + comparative."},
{p:2,tp:"comp",lv:3,s:"The film was nowhere ___ as good as the book.",a:["near"],ex:"nowhere near as … as = much less … than."},
{p:2,tp:"comp",lv:2,s:"It was ___ a beautiful day that we decided to eat outside.",a:["such"],ex:"such + a + adj + noun + that."},
{p:2,tp:"comp",lv:3,s:"The new version is every ___ as reliable as the old one.",a:["bit"],ex:"every bit as … as = just as."},
{p:2,tp:"quant",lv:2,s:"Very ___ people turned up, so the meeting was cancelled.",a:["few"],ex:"few = not many (negative meaning)."},
{p:2,tp:"quant",lv:2,s:"___ of the two proposals was acceptable to the committee, so both were rejected.",a:["neither"],ex:"Neither of the two (+ singular verb) = not one and not the other."},
{p:2,tp:"quant",lv:3,s:"There is a great ___ of evidence to support the theory.",a:["deal"],ex:"a great deal of + uncountable noun."},
{p:2,tp:"pv",lv:2,s:"I'll look ___ the matter and get back to you tomorrow.",a:["into"],ex:"look into = investigate."},
{p:2,tp:"pv",lv:2,s:"I can't put ___ with this noise any longer.",a:["up"],ex:"put up with = tolerate."},
{p:2,tp:"pv",lv:3,s:"He was brought ___ by his grandparents in a small village.",a:["up"],ex:"bring up = raise a child."},
{p:2,tp:"pv",lv:2,s:"We ran ___ of petrol on the motorway.",a:["out"],ex:"run out of = have none left."},
{p:2,tp:"modal",lv:2,s:"You ___ have told me it was your birthday! I'd have bought you a present.",a:["should","could","might","ought"],ex:"should have / could have / might have + pp = criticism of a past action. (ought would need 'to')."},
{p:2,tp:"modal",lv:2,s:"She can't ___ seen us – she didn't even wave.",a:["have"],ex:"can't have + pp = past certainty that something did not happen."},
{p:2,tp:"cond",lv:2,s:"___ you need any further information, please do not hesitate to contact me.",a:["should"],ex:"Should you need = If you need (formal inverted 1st conditional)."},
{p:2,tp:"cond",lv:2,s:"You won't pass ___ you start revising seriously.",a:["unless"],ex:"unless = if … not."},
{p:2,tp:"cond",lv:3,s:"Take a jacket in ___ it gets cold later.",a:["case"],ex:"in case = as a precaution."},
{p:2,tp:"wish",lv:2,s:"It's high time you ___ a decision about your future.",a:["made","took"],ex:"It's (high) time + subject + past simple."},
{p:2,tp:"wish",lv:2,s:"I'd ___ you didn't tell anyone about this.",a:["rather","sooner"],ex:"would rather + subject + past simple."},
{p:2,tp:"verbpat",lv:2,s:"I'm really looking forward ___ seeing you next week.",a:["to"],ex:"look forward to + -ing (to is a preposition)."},
{p:2,tp:"verbpat",lv:2,s:"There's no point ___ complaining now – it's too late.",a:["in"],ex:"There's no point in + -ing."},
{p:2,tp:"pass",lv:2,s:"The bridge is believed ___ have been built by the Romans.",a:["to"],ex:"Reporting passive: be believed to have + pp (past)."},
{p:2,tp:"pass",lv:2,s:"I had my phone ___ while I was on holiday.",a:["stolen","taken"],ex:"have sth done (unpleasant experience)."},
{p:2,tp:"idiom",lv:2,s:"On the ___, the trip was a great success.",a:["whole"],ex:"on the whole = generally."},
{p:2,tp:"idiom",lv:3,s:"They searched for the missing ring, but ___ vain.",a:["in"],ex:"in vain = without success."},
{p:2,tp:"deppr",lv:2,s:"The region is renowned ___ its wines.",a:["for"],ex:"renowned for."},
{p:2,tp:"deppr",lv:2,s:"There has been a sharp increase ___ the number of applications.",a:["in"],ex:"increase IN (the thing that increases); increase OF (the amount)."},
{p:2,tp:"link",lv:3,s:"___ though it was raining, the match went ahead.",a:["even"],ex:"Even though = although (stronger)."},
{p:2,tp:"link",lv:3,s:"I'll support your plan ___ far as I can.",a:["as","so","insofar"],ex:"as far as / so far as = to the extent that."},

/* ---------- PART 3 · word formation ---------- */
{p:3,tp:"wf",lv:2,s:"The ___ of the new motorway has caused years of disruption.",r:"CONSTRUCT",a:["construction"],ex:"Noun after 'the … of': construction."},
{p:3,tp:"wf",lv:2,s:"The instructions were so ___ that nobody knew what to do.",r:"LEAD",a:["misleading"],ex:"Adjective with negative prefix mis- + -ing: misleading."},
{p:3,tp:"wf",lv:3,s:"The changes to the coastline are now considered ___.",r:"REVERSE",a:["irreversible"],ex:"ir- + reverse + -ible (cannot be reversed)."},
{p:3,tp:"wf",lv:2,s:"He showed great ___ to accept the offer.",r:"RELUCTANT",a:["reluctance"],ex:"Noun: reluctant → reluctance."},
{p:3,tp:"wf",lv:2,s:"The ___ of the river at this point is about 200 metres.",r:"WIDE",a:["width"],ex:"wide → width (internal change). Also: long/length, deep/depth, strong/strength."},
{p:3,tp:"wf",lv:3,s:"The film was ___ long and many people left before the end.",r:"BEAR",a:["unbearably"],ex:"Adverb modifying 'long': un + bear + able + ly."},
{p:3,tp:"wf",lv:2,s:"Her ___ in the face of danger impressed everyone.",r:"BRAVE",a:["bravery"],ex:"brave → bravery (noun)."},
{p:3,tp:"wf",lv:3,s:"The water shortage has been made worse by the ___ of rain this spring.",r:"SCARCE",a:["scarcity"],ex:"scarce → scarcity (noun after 'the … of')."},
{p:3,tp:"wf",lv:2,s:"Regular ___ of the equipment is essential for safety.",r:"MAINTAIN",a:["maintenance"],ex:"maintain → maintenance (spelling: -tenance)."},
{p:3,tp:"wf",lv:2,s:"Her ___ is excellent: you'd think English was her first language.",r:"PRONOUNCE",a:["pronunciation"],ex:"pronounce → pronunciation (the 'o' disappears!)."},
{p:3,tp:"wf",lv:3,s:"Many critics have praised the ___ of her approach.",r:"ORIGIN",a:["originality"],ex:"origin → original → originality (quality of being new)."},
{p:3,tp:"wf",lv:2,s:"The weather in the mountains can be highly ___.",r:"PREDICT",a:["unpredictable"],ex:"Adjective with negative prefix: unpredictable."},
{p:3,tp:"wf",lv:3,s:"The minister's comments were widely seen as ___ to the victims.",r:"SENSE",a:["insensitive"],ex:"Negative adjective: insensitive (not 'unsensitive')."},
{p:3,tp:"wf",lv:2,s:"There has been a ___ increase in the number of cyclists.",r:"NOTICE",a:["noticeable"],ex:"Adjective before 'increase': noticeable (keep the e!)."},
{p:3,tp:"wf",lv:3,s:"The new law aims to ___ the rights of tenants.",r:"STRONG",a:["strengthen"],ex:"Verb after 'to': strong → strength → strengthen."},
{p:3,tp:"wf",lv:2,s:"Several ___ for the post were interviewed yesterday.",r:"APPLY",a:["applicants"],ex:"Person noun, plural: applicants."},
{p:3,tp:"wf",lv:3,s:"His ___ remarks only made the situation worse.",r:"THOUGHT",a:["thoughtless"],ex:"Negative adjective with -less: thoughtless."},
{p:3,tp:"wf",lv:2,s:"The museum offers free ___ to students.",r:"ADMIT",a:["admission"],ex:"admit → admission (entry)."},
{p:3,tp:"wf",lv:3,s:"The results of the trial were ___, so further research is needed.",r:"CONCLUDE",a:["inconclusive"],ex:"in- + conclusive."},
{p:3,tp:"wf",lv:2,s:"He was praised for his ___ approach to problem-solving.",r:"IMAGINE",a:["imaginative"],ex:"Adjective = creative: imaginative (≠ imaginary = not real)."},
{p:3,tp:"wf",lv:3,s:"The ___ of local traditions is a priority for the council.",r:"PRESERVE",a:["preservation"],ex:"preserve → preservation."},
{p:3,tp:"wf",lv:2,s:"Her ___ to detail makes her an excellent editor.",r:"ATTEND",a:["attention"],ex:"attend → attention (attention to detail)."},
{p:3,tp:"wf",lv:3,s:"The government's policy proved ___, making the problem even worse.",r:"PRODUCT",a:["counterproductive"],ex:"counter- + productive = having the opposite effect."},
{p:3,tp:"wf",lv:2,s:"She answered the questions with total ___.",r:"CONFIDENT",a:["confidence"],ex:"confident → confidence."},
{p:3,tp:"wf",lv:3,s:"Some of the claims in the article are ___ exaggerated.",r:"GROSS",a:["grossly"],ex:"Adverb: grossly exaggerated (collocation)."},
{p:3,tp:"wf",lv:2,s:"Her ___ to the project never wavered.",r:"COMMIT",a:["commitment"],ex:"commit → commitment (one t before -ment)."},
{p:3,tp:"wf",lv:3,s:"The scheme has been an ___ success.",r:"QUALIFY",a:["unqualified"],ex:"an unqualified success = complete (here un- doesn't mean 'without qualifications')."},
{p:3,tp:"wf",lv:2,s:"A ___ of factors contributed to the decline.",r:"VARY",a:["variety"],ex:"vary → variety (a variety of)."},
{p:3,tp:"wf",lv:3,s:"The athlete's ___ in the final was disappointing.",r:"PERFORM",a:["performance"],ex:"perform → performance."},
{p:3,tp:"wf",lv:3,s:"Many species are threatened by the ___ of their habitats.",r:"DESTROY",a:["destruction"],ex:"destroy → destruction (internal change)."},
{p:3,tp:"wf",lv:2,s:"The staff were ___ friendly and helpful.",r:"EXCEPTION",a:["exceptionally"],ex:"Adverb modifying adjective: exceptionally."},
{p:3,tp:"wf",lv:3,s:"The ___ between the two sides seemed impossible to resolve.",r:"AGREE",a:["disagreement","disagreements"],ex:"dis- + agree + -ment."},
{p:3,tp:"wf",lv:3,s:"The new treatment is ___ more effective than the old one.",r:"SIGNIFY",a:["significantly"],ex:"Adverb before comparative: significantly."},
{p:3,tp:"wf",lv:2,s:"Young adults are staying financially ___ on their parents for longer.",r:"DEPEND",a:["dependent"],ex:"Adjective + on: dependent (≠ dependant, a person you support)."},
{p:3,tp:"wf",lv:3,s:"The company was criticised for its ___ of the risks involved.",r:"ESTIMATE",a:["underestimation"],ex:"under- + estimation (judging something as smaller)."},
{p:3,tp:"wf",lv:2,s:"The team showed remarkable ___ to recover from defeat.",r:"RESILIENT",a:["resilience"],ex:"resilient → resilience."},

/* ---------- PART 4 · key word transformations ---------- */
{p:4,tp:"inv",lv:2,s1:"As soon as we arrived at the station, the train left.",k:"SOONER",s2:"No ___ the station than the train left.",a:["sooner had we arrived at","sooner had we got to","sooner had we reached","sooner had we gotten to"],ex:"No sooner + had + subject + pp … than."},
{p:4,tp:"inv",lv:3,s1:"I only realised how serious it was when I read the report.",k:"DID",s2:"Only when I read the report ___ how serious it was.",a:["did i realise","did i realize","did i understand","did i see"],ex:"Only when + clause, then inversion: did I realise."},
{p:4,tp:"inv",lv:3,s1:"You must not leave the building under any circumstances.",k:"ACCOUNT",s2:"On ___ leave the building.",a:["no account must you","no account should you","no account are you to"],ex:"On no account + inversion (must/should you)."},
{p:4,tp:"inv",lv:2,s1:"If I had known about the meeting, I would have attended.",k:"HAD",s2:"___ about the meeting, I would have attended.",a:["had i known","had i been told","had i heard"],ex:"Inverted 3rd conditional: Had I known."},
{p:4,tp:"inv",lv:3,s1:"She had no idea that her friends were planning a party.",k:"LITTLE",s2:"___ that her friends were planning a party.",a:["little did she know","little did she realise","little did she suspect","little did she realize"],ex:"Little + did + subject + base verb."},
{p:4,tp:"cleft",lv:2,s1:"I was annoyed by his attitude, not his words.",k:"WHAT",s2:"___ his attitude, not his words.",a:["what annoyed me was","what i was annoyed by was","what i found annoying was"],ex:"Wh-cleft: What annoyed me was…"},
{p:4,tp:"cleft",lv:2,s1:"She didn't start painting until she retired.",k:"WAS",s2:"It ___ she started painting.",a:["was only after she retired that","was not until she retired that","wasn't until she retired that","was only when she retired that"],ex:"It wasn't until … that … / It was only after … that …"},
{p:4,tp:"cond",lv:2,s1:"I didn't take the job because the salary was so low.",k:"WOULD",s2:"If the salary hadn't been so low, I ___ the job.",a:["would have taken","would have accepted"],ex:"3rd conditional result: would have + pp."},
{p:4,tp:"cond",lv:3,s1:"Without your help, we would have failed.",k:"BEEN",s2:"If it ___ your help, we would have failed.",a:["had not been for","hadn't been for"],ex:"If it hadn't been for + noun = without."},
{p:4,tp:"cond",lv:2,s1:"You can use my laptop, but you must be careful with it.",k:"LONG",s2:"You can use my laptop ___ careful with it.",a:["as long as you are","so long as you are","as long as you're","so long as you're"],ex:"as long as = on condition that."},
{p:4,tp:"wish",lv:2,s1:"I regret not studying harder for the exam.",k:"WISH",s2:"I ___ harder for the exam.",a:["wish i had studied","wish i'd studied","wish i had worked","wish i'd worked"],ex:"Past regret: wish + past perfect."},
{p:4,tp:"wish",lv:2,s1:"You really should start looking for a job.",k:"TIME",s2:"It's ___ looking for a job.",a:["time you started","high time you started","about time you started"],ex:"It's (high) time + subject + past simple."},
{p:4,tp:"wish",lv:3,s1:"I'd prefer you not to mention this to anyone.",k:"RATHER",s2:"I'd ___ this to anyone.",a:["rather you did not mention","rather you didn't mention"],ex:"would rather + subject + past simple."},
{p:4,tp:"pass",lv:2,s1:"People say that the house is haunted.",k:"SAID",s2:"The house ___ haunted.",a:["is said to be"],ex:"Reporting passive: subject + is said to be."},
{p:4,tp:"pass",lv:3,s1:"It is thought that the fire was caused by an electrical fault.",k:"HAVE",s2:"The fire is thought ___ by an electrical fault.",a:["to have been caused","to have been started"],ex:"Past event → to have been + pp."},
{p:4,tp:"pass",lv:2,s1:"A mechanic is going to repair my car tomorrow.",k:"HAVING",s2:"I'm ___ tomorrow.",a:["having my car repaired","having my car fixed","having the car repaired"],ex:"Causative: have sth done."},
{p:4,tp:"modal",lv:2,s1:"I'm sure she forgot about the meeting.",k:"MUST",s2:"She ___ about the meeting.",a:["must have forgotten"],ex:"Past certainty: must have + pp."},
{p:4,tp:"modal",lv:3,s1:"It wasn't necessary for you to buy a gift, but thank you.",k:"NEEDN'T",s2:"You ___ a gift, but thank you.",a:["needn't have bought","need not have bought","needn't have got"],ex:"needn't have + pp = you did it but it was unnecessary."},
{p:4,tp:"modal",lv:2,s1:"I'm sure he didn't see us.",k:"CAN'T",s2:"He ___ us.",a:["can't have seen","cannot have seen","can't have noticed"],ex:"can't have + pp = certain it didn't happen."},
{p:4,tp:"modal",lv:3,s1:"The parcel was meant to arrive yesterday.",k:"SUPPOSED",s2:"The parcel ___ yesterday.",a:["was supposed to arrive","was supposed to come","was supposed to be delivered"],ex:"be supposed to = be expected to."},
{p:4,tp:"verbpat",lv:2,s1:"I'd prefer not to drive in the dark.",k:"AVOID",s2:"I ___ in the dark.",a:["try to avoid driving","would rather avoid driving","prefer to avoid driving","would like to avoid driving"],ex:"avoid + -ing."},
{p:4,tp:"verbpat",lv:3,s1:"The rain meant we couldn't play the match.",k:"PREVENTED",s2:"The rain ___ the match.",a:["prevented us from playing","prevented us playing"],ex:"prevent sb from + -ing."},
{p:4,tp:"verbpat",lv:3,s1:"He said he hadn't broken the window.",k:"DENIED",s2:"He ___ the window.",a:["denied breaking","denied having broken","denied that he had broken"],ex:"deny + -ing / having + pp."},
{p:4,tp:"pv",lv:2,s1:"The concert has been postponed until next month.",k:"PUT",s2:"The concert ___ until next month.",a:["has been put off","has been put back"],ex:"put off/put back = postpone (passive: has been put off)."},
{p:4,tp:"pv",lv:3,s1:"I can't tolerate his rudeness any longer.",k:"PUT",s2:"I can't ___ his rudeness any longer.",a:["put up with"],ex:"put up with = tolerate."},
{p:4,tp:"pv",lv:3,s1:"She thought of a brilliant idea for the campaign.",k:"CAME",s2:"She ___ a brilliant idea for the campaign.",a:["came up with"],ex:"come up with = think of."},
{p:4,tp:"pv",lv:3,s1:"We have no more coffee left.",k:"RUN",s2:"We have ___ coffee.",a:["run out of"],ex:"run out of = have none left."},
{p:4,tp:"coll",lv:2,s1:"You should consider his age.",k:"ACCOUNT",s2:"You should ___ account.",a:["take his age into"],ex:"take sth into account."},
{p:4,tp:"coll",lv:3,s1:"I always remember to thank the staff.",k:"POINT",s2:"I always ___ the staff.",a:["make a point of thanking"],ex:"make a point of + -ing."},
{p:4,tp:"coll",lv:3,s1:"Nobody noticed the error for weeks.",k:"ATTENTION",s2:"The error didn't ___ for weeks.",a:["come to anyone's attention","come to anybody's attention","come to the attention of anyone"],ex:"come to sb's attention = be noticed."},
{p:4,tp:"idiom",lv:3,s1:"I had no idea what to say.",k:"LOSS",s2:"I was ___ to say.",a:["at a loss as to what","at a loss for what","completely at a loss what"],ex:"at a loss (as to what) = not knowing."},
{p:4,tp:"idiom",lv:3,s1:"It is not at all certain that he will win.",k:"MEANS",s2:"It is ___ that he will win.",a:["by no means certain"],ex:"by no means = not at all."},
{p:4,tp:"comp",lv:2,s1:"The book is much better than the film.",k:"NEARLY",s2:"The film is ___ the book.",a:["not nearly as good as","not nearly so good as"],ex:"not nearly as … as = much less … than."},
{p:4,tp:"comp",lv:3,s1:"If you train harder, you will become fitter.",k:"THE",s2:"___ fitter you will become.",a:["the harder you train, the","the more you train, the"],ex:"The + comparative …, the + comparative."},
{p:4,tp:"comp",lv:3,s1:"The test was so difficult that nobody finished it.",k:"SUCH",s2:"It ___ test that nobody finished it.",a:["was such a difficult"],ex:"such + a + adj + noun + that."},
{p:4,tp:"rep",lv:2,s1:"\"You took my umbrella,\" she said to him.",k:"ACCUSED",s2:"She ___ her umbrella.",a:["accused him of taking","accused him of having taken"],ex:"accuse sb of + -ing."},
{p:4,tp:"rep",lv:3,s1:"\"I'll definitely call you tomorrow,\" he said to me.",k:"PROMISED",s2:"He ___ me the next day.",a:["promised to call","promised that he would call","promised he would call"],ex:"promise to + inf / promise (that) + would."},
{p:4,tp:"deppr",lv:3,s1:"Tourism provides most of the town's income.",k:"ACCOUNTS",s2:"Tourism ___ the town's income.",a:["accounts for most of"],ex:"account for = form (a proportion)."},
{p:4,tp:"link",lv:3,s1:"Although she was tired, she kept working.",k:"SPITE",s2:"In ___ tired, she kept working.",a:["spite of being","spite of feeling","spite of the fact that she was","spite of her being"],ex:"In spite of + -ing / the fact that."},
{p:4,tp:"quant",lv:3,s1:"Only a few people attended the lecture.",k:"HARDLY",s2:"There were ___ at the lecture.",a:["hardly any people","hardly any listeners","hardly any students"],ex:"hardly any + plural noun = almost no."},

/* ---------- PART 5 · short reading inference ---------- */
{p:5,tp:"read",lv:2,s:"“It would be easy to dismiss the novel as yet another coming-of-age story, and on the surface that is exactly what it is. Yet beneath its familiar shape lies something far stranger.”\n\nWhat is the reviewer suggesting?",o:["The novel is more unusual than it first appears.","The novel follows the conventions of its genre too closely.","Readers will find the plot hard to follow.","The novel should not be classified as a coming-of-age story."],a:0,ex:"'Yet beneath its familiar shape lies something far stranger' = there is more to it than it seems. D is too strong: the reviewer accepts that it IS one 'on the surface'."},
{p:5,tp:"read",lv:3,s:"“Few would argue that the museum's new wing lacks ambition. Whether it achieves what it sets out to do is another matter.”\n\nThe writer's attitude to the new wing is",o:["sceptical about its success.","enthusiastic about its design.","critical of its lack of ambition.","uncertain about its purpose."],a:0,ex:"Ambition is conceded; success ('whether it achieves…') is doubted → sceptical. C reverses the meaning of 'few would argue that it lacks ambition'."},
{p:5,tp:"read",lv:2,s:"“I had expected the job to be glamorous. It wasn't – but by the time I realised, I had become far too attached to the people to leave.”\n\nWhy did the writer stay in the job?",o:["because of their relationships with colleagues","because it was more glamorous than expected","because they could not find another job","because they were too busy to look for something else"],a:0,ex:"'too attached to the people to leave' → relationships. A trap option copies 'glamorous'."},
{p:5,tp:"read",lv:3,s:"“The study's conclusions are, on the face of it, compelling. But its sample of thirty volunteers, all drawn from a single university, hardly allows for sweeping claims about humanity at large.”\n\nThe writer criticises the study because",o:["its findings cannot be generalised.","its conclusions are unconvincing.","it involved too many volunteers.","it was carried out by students."],a:0,ex:"Small, narrow sample → can't make 'sweeping claims' = generalise. B contradicts 'on the face of it, compelling'."},
{p:5,tp:"read",lv:2,s:"“Critics have been quick to label the policy a failure. The figures, however, tell a more nuanced story: unemployment has fallen, albeit more slowly than promised.”\n\nThe writer suggests that the critics are",o:["oversimplifying the situation.","completely wrong about the policy.","right that unemployment has risen.","unaware of the figures."],a:0,ex:"'a more nuanced story' = it's not simply a failure. B is too strong because of 'albeit more slowly than promised'."},
{p:5,tp:"read",lv:3,s:"“There is something almost defiant about the way she continues to write by hand, as if the keyboard were an admission of defeat.”\n\nWhat does the writer imply about the woman?",o:["She sees handwriting as a form of resistance.","She is unable to use a computer.","She finds typing physically difficult.","She believes handwriting is faster."],a:0,ex:"'defiant' and 'admission of defeat' → resisting (technology). Nothing about ability or speed."}
];
