/* [term, meaning, example] */
window.PV = [
["account for","explain; form a proportion of","Tourism accounts for 20% of the country's income."],
["back down","withdraw a claim or demand","The council backed down after the protests."],
["back up","support; make a copy of data","Can you back up your argument with evidence?"],
["bank on","rely on","Don't bank on getting a refund."],
["bear out","confirm that something is true","The results bear out our initial theory."],
["bear with","be patient with","Please bear with me for a moment."],
["blow over","pass without serious effect","The scandal soon blew over."],
["boil down to","be essentially about","It all boils down to money."],
["break down","stop working; lose control emotionally; divide into parts","Negotiations broke down in the final hour."],
["break into","enter by force; start doing (a career)","She hopes to break into journalism."],
["break off","end suddenly","They broke off their engagement."],
["break out","start suddenly (war, fire, disease)","A fire broke out in the kitchen."],
["break through","make a discovery; get past an obstacle","Scientists have broken through in cancer research."],
["bring about","cause to happen","The new law brought about major changes."],
["bring forward","move to an earlier date","The meeting has been brought forward to Monday."],
["bring on","cause (something bad)","Stress can bring on headaches."],
["bring up","raise a child; mention a topic","She brought up an interesting point."],
["brush up on","improve a forgotten skill","I need to brush up on my French."],
["call for","demand; require","The situation calls for immediate action."],
["call off","cancel","The match was called off due to rain."],
["carry on","continue","Carry on with your work."],
["carry out","perform (a task, research)","The survey was carried out last year."],
["catch on","become popular; understand","The idea never really caught on."],
["catch up on","do something you haven't had time for","I need to catch up on sleep."],
["come about","happen","How did this situation come about?"],
["come across","find by chance; seem","I came across an old photo. He comes across as arrogant."],
["come down with","become ill with","She came down with flu."],
["come up against","be faced with (a problem)","We came up against strong opposition."],
["come up with","think of (an idea, plan)","She came up with a brilliant solution."],
["count on","depend on","You can always count on me."],
["crack down on","take strong action against","Police are cracking down on speeding."],
["cut back on","reduce","We're cutting back on expenses."],
["cut off","disconnect; isolate","The village was cut off by the snow."],
["cut out","stop doing/eating; be suited","I've cut out sugar. He's not cut out for teaching."],
["die down","become less strong","The wind finally died down."],
["die out","disappear completely","Many traditions are dying out."],
["do away with","abolish","They want to do away with exams."],
["drag on","last longer than expected","The meeting dragged on for hours."],
["draw up","prepare (a document, plan)","The lawyer drew up a contract."],
["drop out","leave (a course, competition)","He dropped out of university."],
["dwell on","think too much about (something negative)","Don't dwell on your mistakes."],
["ease off","become less intense","The rain eased off in the afternoon."],
["end up","finally be in a situation","We ended up staying at home."],
["face up to","accept a difficult reality","You must face up to your responsibilities."],
["fall apart","break into pieces; fail","Their plans fell apart."],
["fall back on","use when other things fail","She has savings to fall back on."],
["fall behind","fail to keep up","He fell behind with his payments."],
["fall for","be deceived by; fall in love with","Don't fall for that old trick."],
["fall out (with)","quarrel","She fell out with her brother."],
["fall through","fail to happen","The deal fell through at the last minute."],
["figure out","understand; solve","I can't figure out how it works."],
["fill in","complete (a form); substitute; inform","Can you fill me in on the details?"],
["get across","communicate successfully","He struggled to get his message across."],
["get around/round","avoid (a rule); spread (news)","There's no way to get round the regulations."],
["get away with","not be punished for","He got away with cheating."],
["get by","manage with difficulty","We get by on very little money."],
["get down to","start doing seriously","Let's get down to business."],
["get on with","have a good relationship; continue","I get on well with my colleagues."],
["get over","recover from","It took her months to get over the illness."],
["get round to","finally find time to do","I never got round to calling him."],
["get through","survive (a difficult time); contact by phone","I couldn't get through to the office."],
["give away","reveal (a secret); give for free","Her expression gave her away."],
["give in","surrender; stop resisting","He finally gave in to the pressure."],
["give off","emit (smell, heat)","The flowers give off a strong scent."],
["give up","stop doing; abandon","She gave up smoking."],
["go along with","agree with","I'll go along with your decision."],
["go back on","break (a promise)","He went back on his word."],
["go off","explode; ring; go bad; stop liking","The milk has gone off."],
["go over","examine/check carefully","Let's go over the figures again."],
["go through","experience (something difficult); examine","She went through a tough time."],
["go without","manage without","We went without food for a day."],
["hand in","submit","Hand in your essays by Friday."],
["hand over","give control/responsibility to","He handed over the company to his son."],
["hang on","wait; hold tightly","Hang on a second."],
["hold back","restrain; hide feelings","She couldn't hold back her tears."],
["hold on to","keep","Hold on to your receipt."],
["hold up","delay; rob","We were held up in traffic."],
["iron out","solve (small problems)","We need to iron out a few details."],
["keep up with","stay at the same level as","It's hard to keep up with technology."],
["lay off","dismiss workers (no fault)","The factory laid off 200 workers."],
["leave out","omit","You've left out an important detail."],
["let down","disappoint","She felt let down by her friends."],
["live up to","meet (expectations)","The film didn't live up to the hype."],
["look down on","consider inferior","Don't look down on people."],
["look into","investigate","The police are looking into the matter."],
["look up to","admire","She has always looked up to her mother."],
["make out","see/hear with difficulty; claim","I couldn't make out what he said."],
["make up","invent; reconcile; form","Women make up 60% of the staff."],
["make up for","compensate for","Nothing can make up for the loss."],
["miss out (on)","lose an opportunity","Don't miss out on this chance."],
["mix up","confuse","I always mix up the twins."],
["opt out (of)","choose not to take part","You can opt out of the scheme."],
["pass away","die (euphemism)","Her grandfather passed away last year."],
["pass up","not take (an opportunity)","I can't pass up an offer like that."],
["pay off","be successful (after effort); repay debt","All that hard work paid off."],
["phase out","gradually stop using","Petrol cars are being phased out."],
["pick up","learn informally; improve; collect","I picked up some Italian on holiday."],
["piece together","reconstruct from fragments","Police pieced together the events."],
["play down","make seem less important","The government played down the risks."],
["point out","draw attention to","She pointed out several errors."],
["pull off","succeed in something difficult","They pulled off a surprising victory."],
["pull through","recover from serious illness","Doctors expect her to pull through."],
["put across","communicate","He put his ideas across clearly."],
["put down to","attribute to","I put his mood down to tiredness."],
["put forward","propose","She put forward a new plan."],
["put off","postpone; discourage","The smell put me off my food."],
["put up with","tolerate","I can't put up with the noise any longer."],
["rule out","exclude as a possibility","Police have ruled out foul play."],
["run into","meet by chance; encounter (problems)","We ran into difficulties early on."],
["run out of","have no more of","We've run out of milk."],
["run up","accumulate (debts, bills)","He ran up huge debts."],
["sail through","pass easily","She sailed through her exams."],
["scale down","reduce in size","The project was scaled down."],
["see through","not be deceived by; continue until finished","I saw through his lies. She saw the project through."],
["set about","begin (a task)","He set about repairing the roof."],
["set back","delay progress; cost","The fire set the project back months."],
["set in","begin and seem likely to continue","Winter has set in."],
["set off","start a journey; cause to explode/start","The alarm was set off by smoke."],
["set out","start a journey; intend","She set out to prove them wrong."],
["set up","establish","They set up a charity."],
["settle down","become calm; start a stable life","He settled down and had a family."],
["single out","choose one for special attention","She was singled out for praise."],
["sink in","be fully understood","The news hasn't sunk in yet."],
["sort out","organise; resolve","Can you sort out this problem?"],
["sound out","find out someone's opinion","I'll sound out the boss on the idea."],
["speak up","speak louder; express opinion","Speak up for what you believe in."],
["stand by","support; keep (a promise)","I'll stand by you whatever happens."],
["stand for","represent; tolerate","What does 'EU' stand for?"],
["stand in for","replace temporarily","She stood in for the manager."],
["stand out","be noticeable","Her talent really stands out."],
["step down","resign","The CEO stepped down last week."],
["step up","increase","Police have stepped up security."],
["stick to","continue with; not change","Stick to the plan."],
["sum up","summarise","To sum up, the project was a success."],
["take after","resemble (a parent)","She takes after her father."],
["take in","deceive; understand; absorb","I couldn't take in all the information."],
["take off","become successful; remove; leave the ground","Her career really took off."],
["take on","employ; accept (a responsibility); compete against","The firm is taking on new staff."],
["take over","gain control of","A larger company took over the firm."],
["take up","start (a hobby); occupy (time/space)","She took up the cello."],
["talk into/out of","persuade to do/not to do","He talked me into buying it."],
["tell apart","distinguish","I can't tell the twins apart."],
["tell off","criticise angrily","The teacher told him off."],
["think over","consider carefully","I'll think it over."],
["throw away","waste (an opportunity)","Don't throw away this chance."],
["tie in with","be connected/consistent with","That ties in with what she said."],
["touch on","mention briefly","The talk touched on climate change."],
["try out","test","We tried out the new software."],
["turn down","refuse; reduce volume","She turned down the job offer."],
["turn out","prove to be; attend","It turned out to be a mistake."],
["turn up","arrive; appear","He turned up late."],
["use up","consume completely","We've used up all our savings."],
["wear off","gradually disappear","The effect of the drug wore off."],
["wear out","exhaust; become unusable","I'm worn out after the trip."],
["weigh up","consider pros and cons","Weigh up the options carefully."],
["wind down","relax; gradually close","The business is winding down."],
["wipe out","destroy completely","The disease wiped out the population."],
["work out","calculate; solve; exercise; turn out","Things worked out well in the end."],
["write off","consider as failed/lost","The car was written off after the crash."],
["zoom in on","focus closely on","The report zooms in on youth unemployment."]
];

window.COLL = [
["pay attention to","notice carefully","Pay close attention to the instructions."],
["pay tribute to","praise publicly","Fans paid tribute to the singer."],
["pay lip service to","say you support without acting","They pay lip service to equality."],
["take into account","consider","Take the weather into account."],
["take for granted","not appreciate; assume","We take clean water for granted."],
["take advantage of","use an opportunity; exploit","Take advantage of the offer."],
["take the initiative","act first without being told","She took the initiative and called them."],
["take a toll on","have a damaging effect","Stress took a toll on his health."],
["take issue with","disagree with","I take issue with that claim."],
["make an effort","try hard","Make an effort to be on time."],
["make a living","earn money to live","He makes a living as a writer."],
["make allowances for","consider special circumstances","Make allowances for her inexperience."],
["make a point of","make sure you do","He makes a point of thanking staff."],
["make headway","make progress","We're making headway with the project."],
["do justice to","show the true quality of","The photo doesn't do justice to the view."],
["do harm / damage","cause harm","Smoking does enormous harm."],
["bear in mind","remember; consider","Bear in mind that it closes early."],
["bear the brunt of","suffer the worst part of","The poor bear the brunt of inflation."],
["bear a resemblance to","look similar to","He bears a striking resemblance to his uncle."],
["draw a conclusion","reach a judgement","It's too early to draw conclusions."],
["draw attention to","make people notice","The campaign drew attention to the issue."],
["draw a distinction","show a difference","We must draw a distinction between them."],
["raise awareness","make people know about","The charity raises awareness of mental health."],
["raise a concern","mention a worry","Parents raised concerns about safety."],
["meet a deadline","finish on time","We struggled to meet the deadline."],
["meet the demand","supply enough","Production can't meet demand."],
["pose a threat","be a danger","Pollution poses a threat to wildlife."],
["pose a question","ask / raise a question","This poses a difficult question."],
["run the risk of","be in danger of","You run the risk of losing everything."],
["reach a compromise","agree after both sides give way","They finally reached a compromise."],
["come to terms with","accept something difficult","She came to terms with her loss."],
["come into effect","start to apply (law)","The rules come into effect in May."],
["come to light","become known","New evidence has come to light."],
["fall into disrepair","become in bad condition","The castle fell into disrepair."],
["hold someone responsible","blame","They held the company responsible."],
["keep a low profile","avoid attention","He's keeping a low profile after the scandal."],
["lose track of","stop knowing about","I lost track of time."],
["place emphasis on","emphasise","The school places emphasis on creativity."],
["play a key role in","be very important in","Diet plays a key role in health."],
["put pressure on","pressurise","Don't put pressure on yourself."],
["set an example","behave as a model","Teachers should set an example."],
["strike a balance","find a good compromise","Strike a balance between work and rest."],
["throw light on","help explain","The study throws light on the problem."],
["gain insight into","understand better","We gained insight into their culture."],
["give rise to","cause","The policy gave rise to protests."],
["have no option but to","be forced to","We had no option but to leave."],
["heavy traffic","lots of traffic","We were stuck in heavy traffic."],
["heavy rain / heavy smoker","intense / frequent","He was a heavy smoker."],
["strong coffee / strong accent","concentrated / noticeable","She has a strong Scottish accent."],
["bitterly disappointed","extremely disappointed","He was bitterly disappointed."],
["highly unlikely","very unlikely","It's highly unlikely to rain."],
["deeply concerned","very worried","We are deeply concerned about this."],
["fully aware","completely aware","I'm fully aware of the risks."],
["utterly ridiculous","completely ridiculous","The idea is utterly ridiculous."],
["painfully slow","very slow (negative)","Progress has been painfully slow."],
["widely regarded as","considered by many as","She is widely regarded as the best."],
["vastly superior","much better","The new model is vastly superior."],
["sorely missed","missed very much","He will be sorely missed."],
["ample opportunity","plenty of opportunity","You'll have ample opportunity to ask."],
["a sharp increase / decline","a sudden big change","There was a sharp increase in prices."],
["a steady rise","a gradual continuous rise","A steady rise in sales."],
["a vicious circle","a bad situation that repeats","Poverty is a vicious circle."],
["a sweeping generalisation","an over-broad statement","That's a sweeping generalisation."],
["a narrow escape","almost not escaping","They had a narrow escape."],
["a heated debate","an angry discussion","There was a heated debate."],
["a rough estimate","an approximate calculation","At a rough estimate, 500 people came."],
["a level playing field","fair conditions for all","We want a level playing field."],
["common knowledge","known by most people","It's common knowledge that…"],
["a growing body of evidence","increasing evidence","A growing body of evidence suggests…"],
["an integral part of","essential part of","Music is an integral part of the course."],
["at the expense of","causing loss to","Profits came at the expense of quality."],
["in the wake of","following, as a result of","In the wake of the crisis…"],
["on the grounds that","for the reason that","He was refused on the grounds that…"],
["with regard to","concerning","With regard to your request…"],
["by virtue of","because of","By virtue of her experience, she was chosen."],
["in light of","considering","In light of recent events…"],
["to a large extent","mostly","To a large extent, I agree."],
["first and foremost","most importantly","First and foremost, safety."],
["by and large","generally","By and large, it went well."],
["leave a lot to be desired","be unsatisfactory","The service left a lot to be desired."],
["stand a chance","have a possibility","We don't stand a chance of winning."],
["break the news","tell bad news","Who will break the news to her?"],
["catch someone's eye","attract attention","The painting caught my eye."],
["follow suit","do the same","Other banks followed suit."],
["go to great lengths","make a big effort","He went to great lengths to help."],
["have a go at","try; criticise","Have a go at this exercise."],
["lend itself to","be suitable for","The novel lends itself to adaptation."],
["meet with approval","be approved","The plan met with approval."],
["pose a challenge","be difficult","Climate change poses a challenge."],
["see eye to eye","agree","We don't always see eye to eye."],
["shed light on","help explain","The diary sheds light on his life."],
["stand to reason","be logical","It stands to reason that prices will rise."]
];

window.IDIOM = [
["at a loss","not knowing what to do/say","I was at a loss for words."],
["by no means","not at all","It is by no means certain."],
["on the verge of","very close to","She was on the verge of tears."],
["in the long run","eventually","It'll save money in the long run."],
["on the spur of the moment","without planning","We left on the spur of the moment."],
["against my better judgement","despite feeling it was unwise","Against my better judgement, I agreed."],
["the icing on the cake","an extra good thing","Winning the prize was the icing on the cake."],
["plain sailing","easy, without problems","It hasn't all been plain sailing."],
["a means to an end","something done only to achieve a goal","The job is just a means to an end."],
["out of the blue","unexpectedly","He called out of the blue."],
["a blessing in disguise","something good that seemed bad","Losing that job was a blessing in disguise."],
["hit the nail on the head","say exactly the right thing","You've hit the nail on the head."],
["once in a blue moon","very rarely","I see him once in a blue moon."],
["in the same boat","in the same difficult situation","We're all in the same boat."],
["get to grips with","begin to understand and deal with","I'm getting to grips with the software."],
["keep on top of","stay in control of","I work late to keep on top of things."],
["learn the ropes","learn how to do a job","It takes time to learn the ropes."],
["by the skin of one's teeth","only just","He passed by the skin of his teeth."],
["call it a day","stop working","Let's call it a day."],
["cut corners","do something badly to save time/money","Don't cut corners on safety."],
["face the music","accept punishment/consequences","He'll have to face the music."],
["get the hang of","learn how to do","You'll soon get the hang of it."],
["go out of one's way","make a special effort","She went out of her way to help."],
["hit it off","like each other immediately","We hit it off straight away."],
["in hot water","in trouble","He's in hot water with his boss."],
["keep an eye on","watch","Keep an eye on the children."],
["let off steam","release energy/anger","Sport helps me let off steam."],
["make ends meet","have just enough money","They struggle to make ends meet."],
["off the top of my head","without checking","Off the top of my head, about 50."],
["on the tip of my tongue","almost remembered","Her name is on the tip of my tongue."],
["pull someone's leg","joke","I'm only pulling your leg."],
["put one's foot down","be firm","Mum put her foot down about bedtime."],
["see the light","finally understand","He finally saw the light."],
["take something with a pinch of salt","not completely believe","Take his stories with a pinch of salt."],
["the last straw","the final problem that makes you lose patience","That was the last straw."],
["under the weather","slightly ill","I'm feeling under the weather."],
["up in the air","undecided","Our plans are still up in the air."],
["word of mouth","informal recommendation","The restaurant grew by word of mouth."],
["have itchy feet","want to travel/move","I've still got itchy feet."],
["live out of a suitcase","travel constantly","I spend my time living out of a suitcase."],
["work someone into the ground","make someone work extremely hard","They worked the players into the ground."],
["out on one's ear","dismissed suddenly","Get it wrong and you'll be out on your ear."],
["win hands down","win easily","The assistant won hands down."],
["ask for the moon","ask for something impossible","You'd think I was asking for the moon!"],
["a far cry from","very different from","This is a far cry from what we expected."],
["at stake","at risk","Our reputation is at stake."],
["bear fruit","produce good results","Our efforts finally bore fruit."],
["by and large","on the whole","By and large, it was a success."],
["come to a head","reach a crisis point","Things came to a head last week."],
["few and far between","rare","Good jobs are few and far between."],
["in the nick of time","just in time","We arrived in the nick of time."],
["in vain","without success","They searched in vain."],
["on the off chance","in case, though unlikely","I called on the off chance she was in."],
["out of the question","impossible","A refund is out of the question."],
["second to none","the best","Their service is second to none."],
["to all intents and purposes","in effect","To all intents and purposes, it's finished."],
["think outside the box","think creatively","We need to think outside the box."],
["turn a blind eye","pretend not to notice","The manager turned a blind eye."],
["with flying colours","very successfully","She passed with flying colours."],
["a drop in the ocean","a tiny amount compared with what is needed","The donation is a drop in the ocean."],
["at the drop of a hat","immediately, without hesitation","He'd travel at the drop of a hat."],
["break the ice","make people feel relaxed","A game helps break the ice."],
["by the same token","for the same reason","By the same token, we should…"],
["get cold feet","become nervous and hesitate","He got cold feet before the wedding."],
["jump at the chance","accept eagerly","I jumped at the chance."],
["pass the buck","shift responsibility","Stop passing the buck."]
];

window.DEPPR = [
["account for","verb","Nothing can account for his behaviour."],["accuse sb of","verb","She was accused of lying."],["adapt to","verb","It took time to adapt to the climate."],["amount to","verb","The costs amount to €5,000."],["apologise for","verb","He apologised for the delay."],["approve of","verb","Her parents don't approve of him."],["attribute sth to","verb","She attributes her success to hard work."],["base on","verb","The film is based on a true story."],["benefit from","verb","Everyone will benefit from the changes."],["blame sb for","verb","Don't blame me for your mistakes."],["comply with","verb","All products must comply with regulations."],["concentrate on","verb","Concentrate on the main points."],["consist of","verb","The team consists of six people."],["contribute to","verb","Many factors contributed to the crisis."],["cope with","verb","How do you cope with stress?"],["deal with","verb","She deals with complaints."],["depend on","verb","It depends on the weather."],["deprive sb of","verb","Prisoners were deprived of sleep."],["differ from","verb","His opinion differs from mine."],["dispose of","verb","Dispose of waste properly."],["engage in","verb","Students engage in debate."],["insist on","verb","She insisted on paying."],["interfere with","verb","Don't interfere with my work."],["object to","verb","I object to being treated like this."],["opt for","verb","Many opt for online courses."],["participate in","verb","Everyone participated in the event."],["prevent sb from","verb","Rain prevented us from leaving."],["refrain from","verb","Please refrain from smoking."],["rely on","verb","You can rely on her."],["resort to","verb","They resorted to violence."],["result in / from","verb","The storm resulted in floods. Floods resulted from the storm."],["specialise in","verb","She specialises in tax law."],["subject sb to","verb","They were subjected to criticism."],["succeed in","verb","He succeeded in convincing them."],["take pride in","verb","She takes pride in her work."],["aware of","adj","Are you aware of the risks?"],["capable of","adj","She is capable of great things."],["committed to","adj","We are committed to quality."],["dependent on","adj","The town is dependent on tourism."],["eligible for","adj","You are eligible for a discount."],["entitled to","adj","You're entitled to a refund."],["familiar with","adj","Are you familiar with the area?"],["immune to","adj","He seems immune to criticism."],["indifferent to","adj","She was indifferent to fame."],["keen on","adj","I'm not keen on spicy food."],["oblivious to/of","adj","He was oblivious to the danger."],["prone to","adj","He is prone to exaggeration."],["reluctant to","adj","She was reluctant to admit it."],["renowned for","adj","The region is renowned for its wine."],["responsible for","adj","Who is responsible for this?"],["sceptical about","adj","I'm sceptical about the claims."],["susceptible to","adj","Children are susceptible to infection."],["tolerant of","adj","Be tolerant of other views."],["access to","noun","Everyone needs access to education."],["alternative to","noun","There is no alternative to hard work."],["approach to","noun","A new approach to teaching."],["attitude towards","noun","Her attitude towards work is great."],["contrast between / with","noun","The contrast between rich and poor."],["demand for","noun","There's a growing demand for electric cars."],["emphasis on","noun","The emphasis on exams is excessive."],["impact on","noun","The impact on wildlife was severe."],["increase / decrease in","noun","An increase in unemployment."],["insight into","noun","The book gives insight into her life."],["lack of","noun","A lack of funding."],["objection to","noun","I have no objection to the plan."],["reason for","noun","What's the reason for the delay?"],["solution to","noun","There's no easy solution to the problem."],["threat to","noun","Plastic is a threat to marine life."],["in charge of","phrase","Who is in charge of marketing?"],["in favour of","phrase","Most were in favour of the plan."],["on behalf of","phrase","I'm writing on behalf of my client."],["with a view to","phrase","…with a view to buying a house."],["at odds with","phrase","His actions are at odds with his words."],["in line with","phrase","Salaries will rise in line with inflation."]
];

/* Confusable word sets: [words, distinction, example] */
window.CONFUS = [
["lack / shortage / absence / scarcity","lack OF (not enough/none); shortage OF (not enough supply); absence = not present; scarcity = rare","a shortage of nurses · a lack of evidence"],
["affect / effect","affect = verb; effect = noun (have an effect on); effect (v) = bring about","The cuts affected everyone. They effected change."],
["raise / rise / arise","raise sth (transitive); rise (intransitive); arise = a problem appears","Prices rose. They raised prices. Problems arose."],
["prevent / avoid / protect","prevent sb FROM doing; avoid doing; protect sb FROM/AGAINST","Masks protect you against infection."],
["job / work / career / occupation","job (countable position); work (uncountable activity); career (life path)","She's looking for work / a job."],
["economic / economical","economic = of the economy; economical = saving money","an economical car · economic growth"],
["sensible / sensitive","sensible = reasonable; sensitive = easily affected / emotional","a sensible decision · sensitive skin"],
["actual / current","actual = real; current = present (false friend: actual ≠ actual!)","the current situation"],
["eventually / finally / at last","eventually = after a long time; at last = relief","Eventually they agreed."],
["remind / remember","remind sb OF/TO; remember (yourself)","Remind me to call her."],
["principal / principle","principal = main/head; principle = moral rule","a matter of principle"],
["comprise / consist / compose / constitute","comprise (no of); consist OF; be composed OF; constitute = form","The team comprises five people."],
["notice / note / remark / observe","notice = see; note = pay attention; remark = comment","Please note that…"],
["argue / discuss / debate","argue (+ about/that); discuss sth (no about!)","We discussed the plan."],
["deny / refuse / reject","deny = say not true; refuse to do; reject an offer/idea","He denied stealing it."],
["exceed / excel / surpass","exceed a limit; excel AT/IN; surpass = be better than","Demand exceeded supply."],
["imply / infer","speaker implies; listener infers","What are you implying?"],
["lie / lay","lie (lay, lain) = be horizontal; lay (laid) sth = put down","She laid the book on the table."],
["expand / extend / enlarge / widen","expand business/range; extend deadline/stay; widen a road/gap","They extended the deadline."],
["possibility / opportunity / chance","opportunity = a good moment to do; possibility OF -ing","a great opportunity to learn"],
["habit / custom / tradition","habit = personal; custom = social practice","It's a local custom."],
["rare / scarce / unusual","rare = not common; scarce = not enough supply","Water is scarce in summer."],
["fault / mistake / error / flaw","fault = responsibility/defect; flaw = weakness in design/character","It's not my fault."],
["persuade / convince","persuade sb TO do; convince sb OF/THAT","She convinced me of her innocence."],
["consistent / constant / continual / continuous","consistent = same standard; continual = repeated; continuous = without stopping","continuous rain"],
["respectable / respectful / respective","respectable = socially acceptable; respectful = showing respect; respective = each","their respective homes"],
["considerate / considerable","considerate = thinking of others; considerable = large","a considerable amount"],
["alternate / alternative","alternate = every other / take turns; alternative = other option","alternate weekends"],
["oversee / overlook","oversee = supervise; overlook = not notice / have a view of","The hotel overlooks the sea."],
["distinguish / differentiate / discriminate","distinguish between / from; discriminate against (unfair)","distinguish right from wrong"]
];

/* Word families for flashcards: [root, family] */
window.WF = [
["able","ability, inability, enable, disabled, unable, ably"],["accept","acceptable, unacceptable, acceptance"],["achieve","achievement, achievable, overachiever"],["admit","admission, admittance, admittedly"],["anxious","anxiety, anxiously"],["apply","applicant, application, applicable, inapplicable"],["argue","argument, argumentative, arguably"],["broad","breadth, broaden, broadly"],["care","careful, careless, carefree, caring"],["choose","choice, choosy"],["compete","competition, competitive, competitor, competence (≠)"],["conclude","conclusion, conclusive, inconclusive"],["courage","courageous, encourage, discourage, encouragement"],["decide","decision, decisive, indecisive, undecided"],["deep","depth, deepen, deeply"],["depend","dependent, independent, dependence, dependable"],["describe","description, descriptive, indescribable"],["destroy","destruction, destructive, indestructible"],["doubt","doubtful, undoubtedly, doubtless"],["effect","effective, ineffective, efficiency, efficient"],["explain","explanation, explanatory, inexplicable"],["fail","failure, unfailing"],["flex","flexible, inflexible, flexibility"],["hesitate","hesitation, hesitant, unhesitatingly"],["imagine","imagination, imaginative, imaginary, unimaginable"],["inform","information, informative, uninformed, misinform"],["know","knowledge, knowledgeable, unknown, unknowingly"],["long","length, lengthen, lengthy, longevity"],["maintain","maintenance"],["notice","noticeable, unnoticed"],["obey","obedient, disobedient, obedience"],["origin","original, originality, originate, originally"],["persuade","persuasion, persuasive, unpersuaded"],["predict","prediction, predictable, unpredictable"],["pronounce","pronunciation, mispronounce"],["reason","reasonable, unreasonable, reasoning"],["rely","reliable, unreliable, reliance, reliability"],["repeat","repetition, repetitive, repeatedly"],["resist","resistance, resistant, irresistible"],["respond","response, responsive, responsibility"],["sacrifice","sacrificial"],["scarce","scarcity, scarcely"],["sign","signature, significant, insignificant, signify"],["strong","strength, strengthen"],["succeed","success, successful, unsuccessful, succession, successive"],["sympathy","sympathetic, unsympathetic, sympathise"],["vary","variety, various, variable, invariably, variation"],["wide","width, widen, widely, widespread"],["willing","unwilling, willingness, unwillingly"],["wise","wisdom, unwise, wisely"]
];
