window.WRITING = [
{id:"e1",type:"Essay",part:1,title:"Funding for young people's free time",prompt:"Your class has attended a panel discussion on how local authorities could spend money to improve young people's free time. You have made the notes below.\n\nWhere should money be spent?\n• sports facilities\n• arts centres\n• youth clubs\n\nSome opinions expressed in the discussion:\n“Young people need somewhere active to go.”\n“Creativity is undervalued.”\n“Clubs keep teenagers off the streets.”\n\nWrite an essay discussing TWO of the areas in your notes. You should explain which area is more important for the authorities to fund, giving reasons in support of your answer. You may, if you wish, make use of the opinions expressed in the discussion, but you should use your own words as far as possible."},
{id:"e2",type:"Essay",part:1,title:"Protecting the environment",prompt:"Your class has watched a documentary on ways individuals can help protect the environment. You have made the notes below.\n\nWays individuals can help:\n• transport choices\n• consumer habits\n• political action\n\nSome opinions expressed in the documentary:\n“Leaving the car at home is the simplest step.”\n“Every purchase is a vote.”\n“Only governments can make a real difference.”\n\nWrite an essay discussing TWO of the ways in your notes. You should explain which way would be more effective, giving reasons in support of your answer."},
{id:"e3",type:"Essay",part:1,title:"Technology in education",prompt:"Your class has had a discussion about how technology has changed education. You have made the notes below.\n\nAreas of change:\n• access to information\n• the role of the teacher\n• students' concentration\n\nSome opinions expressed in the discussion:\n“Everything is just a click away now.”\n“Teachers are becoming facilitators.”\n“Nobody can focus for more than five minutes.”\n\nWrite an essay discussing TWO of the areas in your notes. You should explain which area has been affected more significantly, giving reasons in support of your answer."},
{id:"e4",type:"Essay",part:1,title:"Preserving cultural heritage",prompt:"Your class has attended a lecture on how governments can preserve their country's cultural heritage. You have made the notes below.\n\nHow can governments preserve heritage?\n• funding museums\n• protecting historic buildings\n• supporting traditional crafts\n\nSome opinions expressed in the lecture:\n“Museums bring history to life.”\n“Once a building is gone, it's gone forever.”\n“Crafts are living culture.”\n\nWrite an essay discussing TWO of the methods in your notes. You should explain which method is more important, giving reasons in support of your answer."},
{id:"p1",type:"Proposal",part:2,title:"Improving your college's facilities",prompt:"The principal of your college wants to improve the facilities available to students and has invited proposals. Write a proposal describing the current facilities, explaining what improvements are most needed and how these improvements would benefit students."},
{id:"r1",type:"Report",part:2,title:"A local volunteering scheme",prompt:"You have been involved in a volunteering scheme in your town in which young people help elderly residents. The organisers have asked you to write a report for the town council. In your report, you should describe what the scheme involved, assess how successful it was and recommend how it could be improved in the future."},
{id:"rv1",type:"Review",part:2,title:"A book that changed your perspective",prompt:"An international magazine is inviting readers to submit reviews of a book that changed the way they see the world. Write a review describing the book, explaining how it changed your perspective and saying whether you would recommend it to other young people."},
{id:"l1",type:"Letter",part:2,title:"Complaint to a language school",prompt:"You recently attended a two-week English course at a language school abroad. Several aspects of the course were not as advertised. Write a letter to the director of the school explaining what was disappointing, how it affected your learning and what you would like the school to do."},
{id:"em1",type:"Email",part:2,title:"Job application: summer guide",prompt:"You have seen this advertisement: “Tour guides wanted for our international summer camp. Are you enthusiastic, organised and good with people? Write to us explaining why you would be suitable and what you could contribute to the camp.” Write your email of application."},
{id:"rv2",type:"Review",part:2,title:"A place to study",prompt:"A student website is collecting reviews of places to study outside the home – cafés, libraries or co-working spaces. Write a review of one such place, describing the atmosphere and facilities, explaining what kind of student it would suit best and mentioning any drawbacks."}
];

window.SPEAKING = [
{id:"s1",part:1,title:"Interview",time:"20–30 s per answer",prompt:"Answer each question as you would in the exam (2–3 extended sentences each):\n1. Where are you from, and what do you like most about living there?\n2. What do you enjoy most about studying English?\n3. How do you usually spend your free time?\n4. If you could live anywhere in the world for a year, where would it be and why?"},
{id:"s2",part:2,title:"Long turn: learning new skills",time:"1 minute",prompt:"Your pictures show people learning new skills.\nPicture A: an elderly man taking a computer class in a community centre.\nPicture B: a teenager learning to cook alongside a parent in a home kitchen.\nPicture C: an adult practising rock climbing with an instructor.\n\nCompare TWO of the pictures and say: why the people might want to learn these skills, and how difficult the skills might be to learn."},
{id:"s3",part:2,title:"Long turn: working under pressure",time:"1 minute",prompt:"Your pictures show people working under pressure.\nPicture A: a chef in a busy restaurant kitchen.\nPicture B: an air traffic controller at a radar screen.\nPicture C: a student studying late at night surrounded by books.\n\nCompare TWO of the pictures and say: what kind of pressure the people might be under, and how they might be feeling."},
{id:"s4",part:3,title:"Collaborative: things that make a city liveable",time:"2 min discussion + 1 min decision",prompt:"Here are some things that can make a city a good place to live.\n• public transport • green spaces • cultural events • affordable housing • safety\n\nTalk about how important these things are for making a city a good place to live. (Write both your turns and what you would say to engage your partner.)\nThen decide: which TWO should a city prioritise?"},
{id:"s5",part:4,title:"Discussion: cities and communities",time:"4–5 minutes",prompt:"Answer these follow-up questions with justified opinions:\n1. Do you think people feel lonelier in big cities than in small towns? Why?\n2. Should governments limit the number of tourists who can visit popular cities?\n3. How might cities change in the next fifty years?"}
];
