/* C1 topic vocabulary: [word, part of speech, definition, example, typical collocation] */
window.VOCAB = [
{id:"animals",name:"Animals & the natural world",src:"https://langeek.co/en/vocab/subcategory/915/learn",words:[
["predator","n","an animal that hunts and kills other animals for food","Sharks are the ocean's top predators.","natural / apex predator"],
["prey","n","an animal hunted and killed by another for food","The hawk circled, searching for prey.","fall prey to"],
["habitat","n","the natural home or environment of an animal or plant","Deforestation is destroying the orang-utan's habitat.","natural habitat; habitat loss"],
["endangered","adj","at serious risk of extinction","The snow leopard is an endangered species.","critically endangered"],
["extinct","adj","no longer existing","The dodo became extinct in the 17th century.","become / be driven extinct"],
["breed","v","(of animals) produce young; keep animals to produce young","Pandas rarely breed in captivity.","breed in captivity"],
["domesticated","adj","tamed and kept by humans","Dogs were the first domesticated animals.","domesticated animals"],
["livestock","n","farm animals such as cows, sheep and pigs","The drought killed much of the region's livestock.","rear livestock"],
["migrate","v","move from one region to another according to the season","Swallows migrate south for the winter.","migrate thousands of miles"],
["hibernate","v","spend the winter in a deep sleep","Bears hibernate in caves or dens.","hibernate through the winter"],
["camouflage","n","colouring that makes an animal hard to see against its surroundings","The moth's camouflage makes it almost invisible on bark.","natural camouflage"],
["scavenger","n","an animal that feeds on dead animals or waste","Vultures are scavengers rather than hunters.","opportunistic scavenger"],
["venomous","adj","able to inject poison by biting or stinging","Only a few spiders are venomous to humans.","highly venomous"],
["nocturnal","adj","active at night","Owls are nocturnal hunters.","nocturnal animals"],
["poaching","n","illegal hunting of animals","Poaching has pushed rhinos to the brink.","crack down on poaching"]]},
{id:"environment",name:"Environment & climate",words:[
["emissions","n","gases sent into the air, especially carbon dioxide","The country pledged to cut emissions by half.","cut / curb emissions"],
["sustainable","adj","able to continue without damaging the environment","We need more sustainable farming methods.","sustainable development"],
["deplete","v","use up or reduce the supply of","Overfishing has depleted fish stocks.","deplete resources"],
["renewable","adj","(energy) from a source that is not used up","Wind is a renewable source of energy.","renewable energy"],
["biodiversity","n","the variety of plant and animal life in an area","Rainforests have extraordinary biodiversity.","protect / loss of biodiversity"],
["carbon footprint","n","the amount of CO₂ a person or activity produces","Flying less is the fastest way to reduce your carbon footprint.","reduce your carbon footprint"],
["mitigate","v","make something bad less severe","Planting trees can help mitigate flooding.","mitigate the effects of"],
["drought","n","a long period with little or no rain","The drought has devastated crops.","severe / prolonged drought"],
["landfill","n","a site where rubbish is buried","Most plastic ends up in landfill.","send to landfill"],
["degradation","n","the process of being damaged or made worse","Soil degradation threatens food security.","environmental degradation"],
["conservation","n","the protection of the natural environment","She works for a marine conservation charity.","conservation efforts"],
["pristine","adj","in its original, perfect condition; unspoilt","The island's beaches are pristine.","pristine wilderness"],
["irreversible","adj","impossible to change back","Some damage to the reef may be irreversible.","irreversible damage"],
["phase out","v","gradually stop using","Coal power will be phased out by 2030.","phase out fossil fuels"],
["tipping point","n","the moment when a small change causes a large, unstoppable effect","Scientists fear the ice sheet is near a tipping point.","reach a tipping point"]]},
{id:"work",name:"Work & careers",words:[
["redundant","adj","dismissed because the job is no longer needed","Two hundred staff were made redundant.","be made redundant"],
["promotion","n","a move to a higher position at work","She was passed over for promotion.","be up for / gain promotion"],
["workload","n","the amount of work a person has to do","Teachers complain about their heavy workload.","heavy / manageable workload"],
["freelance","adj","working for different companies rather than one employer","He works as a freelance designer.","go freelance"],
["burnout","n","exhaustion caused by long-term stress at work","Long hours lead to burnout.","suffer from burnout"],
["perk","n","an extra benefit you get from a job","Free lunches are one of the perks of the job.","perks of the job"],
["delegate","v","give part of your work to someone else","Good managers know how to delegate.","delegate tasks / responsibility"],
["vacancy","n","a job that is available","We have a vacancy for a sales assistant.","fill a vacancy"],
["remuneration","n","(formal) payment for work","Remuneration will be commensurate with experience.","competitive remuneration"],
["prospects","n","chances of future success","The job offers good career prospects.","career / job prospects"],
["entrepreneur","n","a person who starts their own business","Young entrepreneurs need access to funding.","budding entrepreneur"],
["meticulous","adj","very careful and precise","She is meticulous in her work.","meticulous attention to detail"],
["headhunt","v","approach someone to offer them a job elsewhere","He was headhunted by a rival firm.","be headhunted"],
["deadline","n","a time by which something must be done","We're working to a tight deadline.","meet / miss a deadline"],
["understaffed","adj","without enough workers","The hospital is chronically understaffed.","chronically understaffed"]]},
{id:"health",name:"Health & medicine",words:[
["sedentary","adj","involving a lot of sitting and little exercise","A sedentary lifestyle increases health risks.","sedentary lifestyle"],
["chronic","adj","lasting for a long time or constantly recurring","She suffers from chronic back pain.","chronic illness / pain"],
["symptom","n","a sign of illness","Fever is a common symptom of flu.","display / alleviate symptoms"],
["diagnosis","n","the identification of an illness","Early diagnosis improves survival rates.","make / receive a diagnosis"],
["alleviate","v","make pain or a problem less severe","The drug helps alleviate pain.","alleviate symptoms / suffering"],
["contagious","adj","spread by contact between people","The virus is highly contagious.","highly contagious"],
["wellbeing","n","the state of being healthy and happy","Exercise improves mental wellbeing.","mental / physical wellbeing"],
["recuperate","v","recover after an illness","He is recuperating at home after surgery.","recuperate from"],
["side effect","n","an unwanted extra effect of a medicine","Drowsiness is a common side effect.","have side effects"],
["immune","adj","protected against a disease","After the vaccine, you are immune to the virus.","immune system; immune to"],
["prescribe","v","(of a doctor) say what medicine someone should take","The doctor prescribed antibiotics.","prescribe medication"],
["malnutrition","n","poor health caused by lack of the right food","Malnutrition remains a problem in the region.","suffer from malnutrition"],
["prevention","n","the act of stopping something from happening","Prevention is better than cure.","disease prevention"],
["outbreak","n","the sudden start of a disease","There has been an outbreak of measles.","an outbreak of"],
["holistic","adj","treating the whole person, not just the symptoms","The clinic takes a holistic approach.","holistic approach"]]},
{id:"technology",name:"Technology & the digital world",words:[
["cutting-edge","adj","the newest and most advanced","The lab uses cutting-edge equipment.","cutting-edge technology"],
["obsolete","adj","no longer used because something newer exists","Fax machines are now obsolete.","become obsolete"],
["breakthrough","n","an important discovery or development","Researchers have made a breakthrough.","make / achieve a breakthrough"],
["automation","n","the use of machines to do work previously done by people","Automation threatens many routine jobs.","increased automation"],
["encryption","n","converting data into a code to protect it","Messages are protected by end-to-end encryption.","data encryption"],
["intrusive","adj","affecting someone's privacy in an unwelcome way","Some apps collect intrusive amounts of data.","intrusive surveillance"],
["user-friendly","adj","easy to use","The interface is very user-friendly.","user-friendly design"],
["glitch","n","a small technical fault","A software glitch delayed the launch.","technical glitch"],
["innovative","adj","using new methods or ideas","It's an innovative solution to an old problem.","highly innovative"],
["addictive","adj","making people want to keep doing it","Social media is designed to be addictive.","highly addictive"],
["upgrade","v","improve a machine or software by replacing it with a newer version","I need to upgrade my phone.","upgrade to"],
["breach","n","a failure to protect something, e.g. data","The data breach affected millions.","data / security breach"],
["streamline","v","make a process simpler and more efficient","The app streamlines online banking.","streamline the process"],
["tech-savvy","adj","good at using modern technology","Younger staff are more tech-savvy.","tech-savvy generation"],
["disruptive","adj","changing an industry completely","Streaming was a disruptive technology for TV.","disruptive innovation"]]},
{id:"society",name:"Society & social issues",words:[
["inequality","n","an unfair situation where some have more than others","Income inequality has grown.","social / income inequality"],
["marginalised","adj","treated as unimportant and excluded","Marginalised communities lack access to services.","marginalised groups"],
["affluent","adj","wealthy","They live in an affluent suburb.","affluent area / society"],
["deprived","adj","lacking basic things such as money, food or housing","The charity works in deprived areas.","socially deprived"],
["stereotype","n","a fixed, oversimplified idea about a group of people","The film challenges gender stereotypes.","challenge / reinforce stereotypes"],
["integration","n","the process of becoming part of a group or society","Language classes help integration.","social integration"],
["welfare","n","help given by the state to people in need","Welfare spending has been cut.","welfare state / benefits"],
["grassroots","adj","involving ordinary people rather than leaders","It began as a grassroots movement.","grassroots campaign"],
["discrimination","n","unfair treatment of a person or group","Discrimination at work is illegal.","racial / age discrimination"],
["urbanisation","n","the movement of people from the countryside to cities","Rapid urbanisation puts pressure on housing.","rapid urbanisation"],
["cohesion","n","the state of a group being united","Shared spaces improve community cohesion.","social cohesion"],
["advocate","v","publicly support an idea or policy","She advocates free school meals.","strongly advocate"],
["controversial","adj","causing a lot of disagreement","The plan is highly controversial.","controversial issue"],
["overcrowded","adj","containing too many people","Prisons are severely overcrowded.","overcrowded cities"],
["consensus","n","general agreement","There is a growing consensus on the issue.","reach a consensus"]]},
{id:"education",name:"Education & learning",words:[
["curriculum","n","the subjects taught in a school or course","Coding is now part of the curriculum.","national curriculum"],
["rote learning","n","learning by repetition without understanding","Rote learning is still common.","rely on rote learning"],
["assessment","n","the process of judging someone's work or ability","Continuous assessment reduces exam stress.","continuous assessment"],
["literacy","n","the ability to read and write","Adult literacy rates have improved.","digital / financial literacy"],
["tuition","n","teaching; the money paid for teaching","Tuition fees have risen sharply.","tuition fees; private tuition"],
["vocational","adj","relating to skills for a particular job","She took a vocational course in nursing.","vocational training"],
["plagiarism","n","copying someone else's work and presenting it as your own","Plagiarism can lead to expulsion.","accuse of plagiarism"],
["mentor","n","an experienced person who advises someone less experienced","Every new student is given a mentor.","act as a mentor"],
["drop out","v","leave school or university before finishing","He dropped out in his second year.","drop out of university"],
["inquisitive","adj","eager to learn and ask questions","Inquisitive children learn faster.","inquisitive mind"],
["grasp","v","understand something, especially something difficult","She quickly grasped the concept.","grasp the idea"],
["proficiency","n","a high level of skill","Applicants need proficiency in English.","language proficiency"],
["extracurricular","adj","outside the normal course of study","He does many extracurricular activities.","extracurricular activities"],
["cram","v","study intensively just before an exam","I crammed all night for the test.","cram for an exam"],
["lifelong learning","n","continuing to learn throughout your life","The library promotes lifelong learning.","promote lifelong learning"]]},
{id:"feelings",name:"Feelings & personality",words:[
["apprehensive","adj","worried that something bad may happen","I felt apprehensive about the interview.","apprehensive about"],
["elated","adj","extremely happy and excited","She was elated by the news.","elated at / by"],
["resilient","adj","able to recover quickly from difficulties","Children are often remarkably resilient.","emotionally resilient"],
["conscientious","adj","careful to do work well and thoroughly","He is a conscientious student.","conscientious worker"],
["arrogant","adj","believing you are better than others","His arrogant attitude annoyed everyone.","arrogant manner"],
["empathy","n","the ability to share another person's feelings","Nurses need empathy.","show / feel empathy"],
["resentful","adj","feeling angry because of unfair treatment","She felt resentful of her sister's success.","resentful of / about"],
["introverted","adj","quiet and preferring to be alone","Introverted people may find networking hard.","rather introverted"],
["impetuous","adj","acting quickly without thinking","His impetuous decision cost him his job.","impetuous by nature"],
["overwhelmed","adj","feeling unable to cope","I felt overwhelmed by the workload.","completely overwhelmed"],
["gullible","adj","easily tricked into believing things","Gullible people fall for scams.","gullible enough to"],
["frustrated","adj","annoyed because you cannot achieve something","She grew frustrated with the delays.","deeply frustrated"],
["self-conscious","adj","nervous about what others think of you","He is self-conscious about his accent.","feel self-conscious"],
["easygoing","adj","relaxed and not easily upset","My flatmate is very easygoing.","easygoing nature"],
["nostalgic","adj","feeling happy and sad when thinking of the past","Old photos make me nostalgic.","nostalgic for"]]},
{id:"media",name:"Media & communication",words:[
["biased","adj","unfairly favouring one side","The report was heavily biased.","biased reporting"],
["sensationalist","adj","presenting news to shock rather than inform","Sensationalist headlines sell papers.","sensationalist press"],
["coverage","n","the reporting of news on a subject","The election got extensive coverage.","media coverage"],
["censorship","n","the control of what can be published or broadcast","The regime imposed strict censorship.","state censorship"],
["misinformation","n","false information, often spread unintentionally","Misinformation spreads quickly online.","spread misinformation"],
["go viral","v","spread very quickly online","The video went viral overnight.","go viral"],
["readership","n","the people who read a newspaper or magazine","The magazine has a young readership.","wide readership"],
["tabloid","n","a popular newspaper with short, sensational stories","Tabloids love celebrity scandals.","tabloid press"],
["influencer","n","someone who affects others' opinions on social media","Brands pay influencers to promote products.","social media influencer"],
["broadcast","v","send out a programme on TV or radio","The match will be broadcast live.","broadcast live"],
["press release","n","an official statement given to journalists","The company issued a press release.","issue a press release"],
["eloquent","adj","speaking or writing fluently and persuasively","She gave an eloquent speech.","eloquent speaker"],
["clickbait","n","online content designed to attract clicks","Clickbait headlines often mislead.","clickbait headline"],
["headline","n","the title of a newspaper story","The story made the headlines.","hit / make the headlines"],
["impartial","adj","not supporting any side","Journalists should remain impartial.","impartial advice"]]},
{id:"science",name:"Science & research",words:[
["hypothesis","n","an idea that is tested by experiments","The results support the hypothesis.","test a hypothesis"],
["empirical","adj","based on observation or experiment","There is little empirical evidence.","empirical evidence / data"],
["sample","n","a small group used to represent a larger one","The sample was too small to be reliable.","representative sample"],
["replicate","v","repeat an experiment to check results","Other labs failed to replicate the findings.","replicate results"],
["peer review","n","evaluation of research by other experts","The paper is undergoing peer review.","peer-reviewed journal"],
["variable","n","a factor that can change in an experiment","We controlled every variable.","control a variable"],
["findings","n","the results of research","The findings were published in Nature.","research findings"],
["conclusive","adj","proving something beyond doubt","The evidence is not conclusive.","conclusive proof"],
["anomaly","n","something that differs from what is expected","The data showed a strange anomaly.","statistical anomaly"],
["correlation","n","a connection between two things","There is a correlation between diet and mood.","strong correlation between"],
["groundbreaking","adj","very new and important","Her research was groundbreaking.","groundbreaking discovery"],
["inconclusive","adj","not leading to a firm conclusion","The trial was inconclusive.","inconclusive results"],
["breakthrough","n","a sudden important discovery","A breakthrough in cancer research.","major breakthrough"],
["methodology","n","a set of methods used in a study","Critics questioned the methodology.","research methodology"],
["ethical","adj","relating to what is morally right","Animal testing raises ethical issues.","ethical concerns"]]},
{id:"arts",name:"Arts & culture",words:[
["acclaimed","adj","publicly praised","The critically acclaimed film won three awards.","critically acclaimed"],
["exhibition","n","a public display of art or objects","The exhibition runs until June.","hold / stage an exhibition"],
["masterpiece","n","an outstanding work of art","The painting is considered a masterpiece.","a true masterpiece"],
["plot","n","the main events of a story","The plot is full of twists.","plot twist"],
["portray","v","show or describe someone in a particular way","The actor portrays a troubled detective.","portray as"],
["abstract","adj","not representing things realistically","She prefers abstract art.","abstract painting"],
["heritage","n","traditions and buildings from a country's past","The city has a rich cultural heritage.","cultural heritage"],
["captivating","adj","holding your attention completely","Her performance was captivating.","captivating performance"],
["pretentious","adj","trying to seem more important or clever than you are","The dialogue felt pretentious.","rather pretentious"],
["genre","n","a style or category of art, music or writing","Crime fiction is my favourite genre.","literary genre"],
["adaptation","n","a film or play based on a book","The adaptation is faithful to the novel.","screen / film adaptation"],
["rehearsal","n","a practice before a performance","The choir has rehearsals twice a week.","dress rehearsal"],
["thought-provoking","adj","making people think seriously","It's a thought-provoking documentary.","thought-provoking film"],
["patron","n","a person who supports artists financially","The Medici were great patrons of the arts.","patron of the arts"],
["cliché","n","an idea or phrase used so often it lacks originality","The ending was a cliché.","full of clichés"]]},
{id:"money",name:"Money, business & the economy",words:[
["recession","n","a period when the economy shrinks","The country entered a recession.","go into recession"],
["inflation","n","a general rise in prices","Inflation reached 10%.","high / rising inflation"],
["revenue","n","income, especially of a company or government","Advertising revenue fell.","generate revenue"],
["bankrupt","adj","unable to pay debts","The firm went bankrupt.","go bankrupt"],
["thrifty","adj","careful with money","My thrifty grandparents never wasted anything.","thrifty habits"],
["lucrative","adj","producing a lot of money","She left a lucrative career in law.","lucrative deal / market"],
["merger","n","the joining of two companies","The merger created a global giant.","announce a merger"],
["consumerism","n","a culture focused on buying goods","The film criticises consumerism.","rampant consumerism"],
["overheads","n","regular costs of running a business","Working from home cuts overheads.","reduce overheads"],
["boom","n","a period of rapid economic growth","The property boom pushed prices up.","economic boom"],
["subsidise","v","pay part of the cost to reduce prices","The government subsidises public transport.","heavily subsidised"],
["debt","n","money that is owed","Many students graduate in debt.","get into / pay off debt"],
["affordable","adj","cheap enough for people to buy","There's a shortage of affordable housing.","affordable housing"],
["invest","v","put money into something to make a profit","They invested in renewable energy.","invest heavily in"],
["fluctuate","v","change frequently in amount","Prices fluctuate with demand.","fluctuate wildly"]]},
{id:"travel",name:"Travel & places",words:[
["itinerary","n","a planned route or journey","Our itinerary includes three cities.","detailed itinerary"],
["picturesque","adj","attractive, like a painting","They stayed in a picturesque village.","picturesque setting"],
["off the beaten track","phrase","far away from places people usually visit","We found a café off the beaten track.","go off the beaten track"],
["breathtaking","adj","extremely beautiful or impressive","The view was breathtaking.","breathtaking scenery"],
["commute","v","travel regularly between home and work","She commutes an hour each way.","daily commute"],
["accommodation","n","a place to stay","Accommodation is included in the price.","find / book accommodation"],
["excursion","n","a short trip for pleasure","We went on an excursion to the lakes.","day excursion"],
["bustling","adj","full of busy activity","The market was bustling with tourists.","bustling city"],
["remote","adj","far away from towns","They live in a remote village.","remote area"],
["jet lag","n","tiredness after a long flight","I'm still suffering from jet lag.","get over jet lag"],
["overrated","adj","thought to be better than it really is","The famous restaurant was overrated.","vastly overrated"],
["landmark","n","a famous building or feature","The tower is the city's best-known landmark.","historic landmark"],
["wanderlust","n","a strong desire to travel","Her wanderlust took her to 40 countries.","be bitten by wanderlust"],
["sprawl","n","the uncontrolled spread of a city","Urban sprawl swallowed the farmland.","urban sprawl"],
["cosmopolitan","adj","including people from many countries","Montevideo is a cosmopolitan city.","cosmopolitan atmosphere"]]}
];
